-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 15:42:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema repair_agency
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `repair_agency` ;

-- -----------------------------------------------------
-- Schema repair_agency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `repair_agency` DEFAULT CHARACTER SET utf8 ;
USE `repair_agency` ;

-- -----------------------------------------------------
-- Table `repair_agency`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`roles` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '1 - SYSADMIN, 2 - ADMIN, 3 - MANAGER, 4 - MASTER',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`repair_shops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`repair_shops` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`repair_shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`users` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repair_shop` INT NOT NULL,
  `t` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `u_role_idx` (`t` ASC),
  INDEX `u_repair_shop_idx` (`repair_shop` ASC),
  CONSTRAINT `u_role`
    FOREIGN KEY (`t`)
    REFERENCES `repair_agency`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `u_repair_shop`
    FOREIGN KEY (`repair_shop`)
    REFERENCES `repair_agency`.`repair_shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`repair_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`repair_services` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`repair_services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `repair_shop` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `rs_repair_shop_idx` (`repair_shop` ASC),
  CONSTRAINT `rs_repair_shop`
    FOREIGN KEY (`repair_shop`)
    REFERENCES `repair_agency`.`repair_shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`repair_devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`repair_devices` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`repair_devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `repair_services` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `rd_repair_services_idx` (`repair_services` ASC),
  CONSTRAINT `rd_repair_services`
    FOREIGN KEY (`repair_services`)
    REFERENCES `repair_agency`.`repair_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`repair_service_kinds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`repair_service_kinds` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`repair_service_kinds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `repair_service` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `rsk_repair_service_idx` (`repair_service` ASC),
  CONSTRAINT `rsk_repair_service`
    FOREIGN KEY (`repair_service`)
    REFERENCES `repair_agency`.`repair_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`device_phisical_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`device_phisical_states` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`device_phisical_states` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '1 - новий, 2 - потертій, 3 - пошкоджений',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`order_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`order_types` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`order_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '1 - Платний, 2 - Гарантійний',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`order_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`order_statuses` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`order_statuses` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '1 - НОВИЙ, 2 - В РОБОТІ, ВІДКЛАДЕНИЙ,  ВИКОНАНИЙ, ЗАКРИТИЙ, ВІДХИЛЕНИЙ',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`clients` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repair_shop` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `memo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `c_repair_shop_idx` (`repair_shop` ASC),
  CONSTRAINT `c_repair_shop`
    FOREIGN KEY (`repair_shop`)
    REFERENCES `repair_agency`.`repair_shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`device` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repair_shop` INT NOT NULL,
  `client` INT NOT NULL,
  `device_name` VARCHAR(45) NOT NULL,
  `brand_name` VARCHAR(45) NULL,
  `model_name` VARCHAR(45) NULL,
  `serial_number` VARCHAR(45) NULL,
  `memo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `d_repair_shop_idx` (`repair_shop` ASC),
  INDEX `d_client_idx` (`client` ASC),
  CONSTRAINT `d_repair_shop`
    FOREIGN KEY (`repair_shop`)
    REFERENCES `repair_agency`.`repair_shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `d_client`
    FOREIGN KEY (`client`)
    REFERENCES `repair_agency`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`orders` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_type` INT NOT NULL,
  `repair_shop` INT NOT NULL,
  `repair_service` INT NOT NULL,
  `repair_service_kind` INT NOT NULL,
  `repair_device` INT NOT NULL,
  `creator` INT NOT NULL,
  `executor` INT NOT NULL,
  `status` INT NOT NULL,
  `client` INT NOT NULL,
  `device` INT NOT NULL,
  `defect` VARCHAR(255) NOT NULL,
  `device_phisical_state` INT NOT NULL,
  `memo` VARCHAR(255) NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `deadline_date` DATETIME NOT NULL,
  `urgent` TINYINT NULL,
  `price` DECIMAL NULL,
  `prapaid` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `o_order_type_idx` (`order_type` ASC),
  INDEX `o_repair_shop_idx` (`repair_shop` ASC),
  INDEX `o_repair_service_idx` (`repair_service` ASC),
  INDEX `0_repair_device_idx` (`repair_device` ASC),
  INDEX `o_manager_idx` (`creator` ASC),
  INDEX `o_executor_idx` (`executor` ASC),
  INDEX `o_status_idx` (`status` ASC),
  INDEX `o_client_idx` (`client` ASC),
  INDEX `o_phisical_state_idx` (`device_phisical_state` ASC),
  INDEX `o_device_idx` (`device` ASC),
  INDEX `o_repair_service_kind_idx` (`repair_service_kind` ASC),
  CONSTRAINT `o_order_type`
    FOREIGN KEY (`order_type`)
    REFERENCES `repair_agency`.`order_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_repair_shop`
    FOREIGN KEY (`repair_shop`)
    REFERENCES `repair_agency`.`repair_shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_repair_service`
    FOREIGN KEY (`repair_service`)
    REFERENCES `repair_agency`.`repair_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_repair_device`
    FOREIGN KEY (`repair_device`)
    REFERENCES `repair_agency`.`repair_devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_creator`
    FOREIGN KEY (`creator`)
    REFERENCES `repair_agency`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_executor`
    FOREIGN KEY (`executor`)
    REFERENCES `repair_agency`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_status`
    FOREIGN KEY (`status`)
    REFERENCES `repair_agency`.`order_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_client`
    FOREIGN KEY (`client`)
    REFERENCES `repair_agency`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_device`
    FOREIGN KEY (`device`)
    REFERENCES `repair_agency`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_device_phisical_state`
    FOREIGN KEY (`device_phisical_state`)
    REFERENCES `repair_agency`.`device_phisical_states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_repair_service_kind`
    FOREIGN KEY (`repair_service_kind`)
    REFERENCES `repair_agency`.`repair_service_kinds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `repair_agency`.`order_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repair_agency`.`order_history` ;

CREATE TABLE IF NOT EXISTS `repair_agency`.`order_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repair_shop` INT NOT NULL,
  `order` INT NOT NULL,
  `status` INT NOT NULL,
  `executor` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `oh_repair_shop_idx` (`repair_shop` ASC),
  INDEX `oh_order_idx` (`order` ASC),
  INDEX `oh_status_idx` (`status` ASC),
  INDEX `oh_executor_idx` (`executor` ASC),
  CONSTRAINT `oh_repair_shop`
    FOREIGN KEY (`repair_shop`)
    REFERENCES `repair_agency`.`repair_shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oh_order`
    FOREIGN KEY (`order`)
    REFERENCES `repair_agency`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oh_status`
    FOREIGN KEY (`status`)
    REFERENCES `repair_agency`.`order_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oh_executor`
    FOREIGN KEY (`executor`)
    REFERENCES `repair_agency`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
